In [13]:
import json, pandas as pd
frames = pd.DataFrame(json.load(open("frame.json")))
frames.head(5)

,name,brand,product_code,variant_id,variant_title,component_type,site_category,price,compare_at,currency,weight_grams,shipping_grams,options,specs,spec_notes,description,image_url,source_url,frame_brake_drilled,fork_brake_drilled
0,Skream Magnum frameset - Lime - XS (51cm),Skream Bikes,MAGNUMLMXS,43317309734973,XS (51cm),frame,Framesets,699.0,False,USD,1550,7257,{'size': 'XS (51cm)'},{'frame': '6066-T6 AL w/ stainless steel dropo...,"[includes Skream IS42/52 integrated headset, c...","Made of strong, light 6066 triple butted alumi...",https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/skream...,True,True
1,Skream Magnum frameset - Lime - S (54cm),Skream Bikes,MAGNUMLMS,43317309767741,S (54cm),frame,Framesets,699.0,False,USD,1550,7257,{'size': 'S (54cm)'},{'frame': '6066-T6 AL w/ stainless steel dropo...,"[includes Skream IS42/52 integrated headset, c...","Made of strong, light 6066 triple butted alumi...",https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/skream...,True,True
2,Skream Magnum frameset - Lime - M (56cm),Skream Bikes,MAGNUMLMM,43317309800509,M (56cm),frame,Framesets,699.0,False,USD,1550,7257,{'size': 'M (56cm)'},{'frame': '6066-T6 AL w/ stainless steel dropo...,"[includes Skream IS42/52 integrated headset, c...","Made of strong, light 6066 triple butted alumi...",https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/skream...,True,True
3,Skream Magnum frameset - Lime - L (59cm),Skream Bikes,MAGNUMLML,43317309833277,L (59cm),frame,Framesets,699.0,False,USD,1550,7257,{'size': 'L (59cm)'},{'frame': '6066-T6 AL w/ stainless steel dropo...,"[includes Skream IS42/52 integrated headset, c...","Made of strong, light 6066 triple butted alumi...",https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/skream...,True,True
4,Skream Magnum frameset - Lime - XL (61cm),Skream Bikes,MAGNUMLMXL,43317309866045,XL (61cm),frame,Framesets,699.0,False,USD,1550,7257,{'size': 'XL (61cm)'},{'frame': '6066-T6 AL w/ stainless steel dropo...,"[includes Skream IS42/52 integrated headset, c...","Made of strong, light 6066 triple butted alumi...",https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/skream...,True,True

In [14]:
frames = frames.drop(columns=["product_code",  "compare_at", "site_category", "shipping_grams", "spec_notes", "variant_id", "options"])
frames = frames.rename(columns={"variant_title": "size (cm)"})

frames.head()

,name,brand,size (cm),component_type,price,currency,weight_grams,specs,description,image_url,source_url,frame_brake_drilled,fork_brake_drilled
0,Skream Magnum frameset - Lime - XS (51cm),Skream Bikes,XS (51cm),frame,699.0,USD,1550,{'frame': '6066-T6 AL w/ stainless steel dropo...,"Made of strong, light 6066 triple butted alumi...",https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/skream...,True,True
1,Skream Magnum frameset - Lime - S (54cm),Skream Bikes,S (54cm),frame,699.0,USD,1550,{'frame': '6066-T6 AL w/ stainless steel dropo...,"Made of strong, light 6066 triple butted alumi...",https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/skream...,True,True
2,Skream Magnum frameset - Lime - M (56cm),Skream Bikes,M (56cm),frame,699.0,USD,1550,{'frame': '6066-T6 AL w/ stainless steel dropo...,"Made of strong, light 6066 triple butted alumi...",https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/skream...,True,True
3,Skream Magnum frameset - Lime - L (59cm),Skream Bikes,L (59cm),frame,699.0,USD,1550,{'frame': '6066-T6 AL w/ stainless steel dropo...,"Made of strong, light 6066 triple butted alumi...",https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/skream...,True,True
4,Skream Magnum frameset - Lime - XL (61cm),Skream Bikes,XL (61cm),frame,699.0,USD,1550,{'frame': '6066-T6 AL w/ stainless steel dropo...,"Made of strong, light 6066 triple butted alumi...",https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/skream...,True,True

In [6]:
frames.head(2)

,name,brand,size (cm),component_type,price,currency,weight_grams,description,image_url,source_url,frame_brake_drilled,fork_brake_drilled
0,Skream Magnum frameset - Lime - XS (51cm),Skream Bikes,XS (51cm),frame,699.0,USD,1550,"Made of strong, light 6066 triple butted alumi...",https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/skream...,True,True
1,Skream Magnum frameset - Lime - S (54cm),Skream Bikes,S (54cm),frame,699.0,USD,1550,"Made of strong, light 6066 triple butted alumi...",https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/skream...,True,True

In [15]:
frames["name"] = frames["name"].str.extract(r"^(.*) - .+$")
frames.head()

,name,brand,size (cm),component_type,price,currency,weight_grams,specs,description,image_url,source_url,frame_brake_drilled,fork_brake_drilled
0,Skream Magnum frameset - Lime,Skream Bikes,XS (51cm),frame,699.0,USD,1550,{'frame': '6066-T6 AL w/ stainless steel dropo...,"Made of strong, light 6066 triple butted alumi...",https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/skream...,True,True
1,Skream Magnum frameset - Lime,Skream Bikes,S (54cm),frame,699.0,USD,1550,{'frame': '6066-T6 AL w/ stainless steel dropo...,"Made of strong, light 6066 triple butted alumi...",https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/skream...,True,True
2,Skream Magnum frameset - Lime,Skream Bikes,M (56cm),frame,699.0,USD,1550,{'frame': '6066-T6 AL w/ stainless steel dropo...,"Made of strong, light 6066 triple butted alumi...",https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/skream...,True,True
3,Skream Magnum frameset - Lime,Skream Bikes,L (59cm),frame,699.0,USD,1550,{'frame': '6066-T6 AL w/ stainless steel dropo...,"Made of strong, light 6066 triple butted alumi...",https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/skream...,True,True
4,Skream Magnum frameset - Lime,Skream Bikes,XL (61cm),frame,699.0,USD,1550,{'frame': '6066-T6 AL w/ stainless steel dropo...,"Made of strong, light 6066 triple butted alumi...",https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/skream...,True,True

In [16]:
frames = (
    frames
    .groupby(["name", "image_url", "source_url"], as_index=False)
    .agg({
        "brand": "first",
        "component_type": "first",
        "price": "first",
        "currency": "first",
        "weight_grams": "first",
        "description": "first",
        "frame_brake_drilled": "first",
        "fork_brake_drilled": "first",
        "specs": "first",
        "size (cm)": list,
    })
    .rename(columns={"size (cm)": "sizes"})
)
frames.head()

,name,image_url,source_url,brand,component_type,price,currency,weight_grams,description,frame_brake_drilled,fork_brake_drilled,specs,sizes
0,Cinelli Vigorelli AL frameset - 80s National Blu,https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/cinell...,Cinelli,frame,1299.0,USD,350,Vigorelli legacy takes you back where everythi...,True,True,"{'frame/fork spacing': '120/100mm', 'BB': '68m...","[XS, S, M, L, XL]"
1,Cinelli Vigorelli ST frameset - 80s Team Red/W...,https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/cinell...,Cinelli,frame,1099.0,USD,350,"The Cinelli Vigorelli Steel, introduced to the...",True,True,"{'frame/fork spacing': '120/100mm', 'BB': '68m...","[XS, S, M, L, XL]"
2,Dolan Pre Cursa frameset - Chameleon Purple,https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/dolan-...,Dolan,frame,695.0,USD,1780,The updated Dolan Pre Cursa features a tapered...,False,True,{'frame': '7075 AL triple butted w/ oversized ...,"[50cm, 52cm, 54cm, 56cm, 58cm, 60cm]"
3,Dolan Pre Cursa frameset - Starlight Black,https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/dolan-...,Dolan,frame,695.0,USD,1780,The updated Dolan Pre Cursa features a tapered...,False,True,{'frame': '7075 AL triple butted w/ oversized ...,"[50cm, 52cm, 54cm, 56cm, 58cm, 60cm]"
4,Ritchey Garden City Track frameset,https://cdn.shopify.com/s/files/1/0836/4641/fi...,https://www.retro-gression.com/products/ritche...,Ritchey,frame,1349.0,USD,1950,"They say less is more, and the Ritchey Garden ...",True,True,"{'frame': 'heat-treated, triple-butted Ritchey...","[S (48cm), M (51cm), L (54cm), XL (57cm)]"

In [17]:
import re

def tire_clearance(specs):
    text = " ".join(v for k, v in specs.items() if "tire" in k.lower() or "clear" in k.lower())
    nums = [int(n) for n in re.findall(r"(\d{2,3})\s*mm", text)]
    return min(nums) if nums else None

frames["max_tire_clearance_mm"] = frames["specs"].apply(tire_clearance)
frames[["name", "max_tire_clearance_mm"]].head(10)

                                                name  max_tire_clearance_mm
0   Cinelli Vigorelli AL frameset - 80s National Blu                   28.0
1  Cinelli Vigorelli ST frameset - 80s Team Red/W...                   28.0
2        Dolan Pre Cursa frameset - Chameleon Purple                    NaN
3         Dolan Pre Cursa frameset - Starlight Black                    NaN
4                 Ritchey Garden City Track frameset                    NaN
5                      Skream Magnum frameset - Dune                   35.0
6                    Skream Magnum frameset - Lagoon                   35.0
7                      Skream Magnum frameset - Lime                   35.0
8           Skream Magnum frameset - Midnight Purple                   35.0
9                     Skream Magnum frameset - Shade                   35.0

## Crankset